version: "3"
services:
  db-raven:
    image: ravendb/ravendb:ubuntu-latest
    restart: always
    ports:
      - 4000:8080
    volumes:
      - database-raven:/opt/RavenDB/config
  db-postgres-server:
    image: postgres:13.7-alpine3.16
    restart: always
    ports:
      - 4001:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_SCHEMA}
    volumes:
      - database-postgres:/var/lib/postgresql/data
  db-mysql-server:
    image: mysql:latest
    restart: always
    ports:
      - 4002:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_SCHEMA}
    volumes:
      - database-mysql:/var/lib/mysql
  db-mongo-server:
    image: mongo:latest
    restart: always
    ports:
      - 4003:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - database-mongo:/etc/mongo
  mongo-express-service:
    image: mongo-express:latest
    restart: always
    ports:
      - 4004:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH_USERNAME: iargueta
      ME_CONFIG_BASICAUTH_PASSWORD: iorbix
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASS}@db-mongo-server:27017/
volumes:
  database-raven:
    driver: local
  database-postgres:
    driver: local
  database-mysql:
    driver: local
  database-mongo:
    driver: local